"""timestampmixins

Revision ID: 4a552ed1dcb2
Revises: b76ed59bd64f
Create Date: 2020-05-13 10:07:36.619876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a552ed1dcb2'
down_revision = 'b76ed59bd64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('project', 'updated_at')
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
