"""todo table

Revision ID: 9f8e31fbdac7
Revises: 3920d7bf2d47
Create Date: 2020-05-14 07:28:02.301787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8e31fbdac7'
down_revision = '3920d7bf2d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=140), nullable=False),
    sa.Column('edate', sa.DateTime(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_edate'), 'todo', ['edate'], unique=False)
    op.create_index(op.f('ix_todo_task'), 'todo', ['task'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_task'), table_name='todo')
    op.drop_index(op.f('ix_todo_edate'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
