"""artifacts table

Revision ID: fd3321e5217b
Revises: 9f8e31fbdac7
Create Date: 2020-05-14 09:03:25.918437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3321e5217b'
down_revision = '9f8e31fbdac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('file', sa.String(length=60), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_file'), 'artifact', ['file'], unique=False)
    op.create_index(op.f('ix_artifact_name'), 'artifact', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_name'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_file'), table_name='artifact')
    op.drop_table('artifact')
    # ### end Alembic commands ###
